name: Release cli libs

on:
  release:
    types: [published]

jobs:
  build:
    name: Release cli libs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build binaries
        run: deno compile -A --unstable --output apps/cli/dist/cli ./apps/cli/mod.ts

      - name: Rename MacOS binary
        if: runner.os == 'MacOS'
        run: mv apps/cli/dist/cli apps/cli/dist/cli-darwin

      - name: Zip MacOS binary
        if: runner.os == 'MacOS'
        uses: vimtor/action-zip@v1
        with:
          files: apps/cli/dist/cli-darwin
          dest: cli-macos.zip

      - name: Rename Linux binary
        if: runner.os == 'Linux'
        run: mv apps/cli/dist/cli apps/cli/dist/cli-linux

      - name: Zip Linux binary
        if: runner.os == 'Linux'
        uses: vimtor/action-zip@v1
        with:
          files: apps/cli/dist/cli-linux
          dest: cli-linux.zip

      - name: Rename Windows binary
        if: runner.os == 'Windows'
        run: mv apps/cli/dist/cli.exe apps/cli/dist/cli-windows.exe

      - name: Zip Windows binary
        if: runner.os == 'Windows'
        uses: vimtor/action-zip@v1
        with:
          files: apps/cli/dist/cli-windows.exe
          dest: cli-windows.zip

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Publish to pm
        run: |
          cd apps/cli
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Release binaries
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: BigDog1400/code0
          repo_token: ${{ secrets.TOKEN }}
          files: |
            cli-macos.zip
            cli-linux.zip
            cli-windows.zip
          tag: ${{ github.event.release.tag_name }}
          overwrite: true
