name: Release cli libs

on:
  release:
    types: [published]

jobs:
  build:
    name: Release cli libs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Build binaries
        run: deno compile -A --unstable --output apps/cli/dist/cli ./apps/cli/mod.ts

      - name: Rename MacOS binary
        if: runner.os == 'MacOS'
        run: mv apps/cli/dist/cli apps/cli/dist/cli-darwin

      - name: Upload MacOS Binary
        if: runner.os == 'MacOS'
        uses: actions/upload-artifact@v3
        with:
          name: cli-darwin
          path: apps/cli/dist/cli-darwin

      - name: Zip MacOS binary
        if: runner.os == 'MacOS'
        uses: vimtor/action-zip@v1
        with:
          files: apps/cli/dist/cli-darwin
          dest: cli.zip

      - name: Release MacOS binary Zip
        if: runner.os == 'MacOS'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: BigDog1400/code0
          repo_token: ${{ secrets.TOKEN }}
          file: cli.zip
          tag: ${{ github.event.release.tag_name }}
          asset_name: cli-macos.zip
          overwrite: true

      - name: Rename Linux binary
        if: runner.os == 'Linux'
        run: mv apps/cli/dist/cli apps/cli/dist/cli-linux

      - name: Upload Linux Binary
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: cli-linux
          path: apps/cli/dist/cli-linux

      - name: Zip Linux binary
        if: runner.os == 'Linux'
        uses: vimtor/action-zip@v1
        with:
          files: apps/cli/dist/cli-linux
          dest: cli.zip

      - name: Release Linux binary Zip
        if: runner.os == 'Linux'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: BigDog1400/code0
          repo_token: ${{ secrets.TOKEN }}
          file: cli.zip
          tag: ${{ github.event.release.tag_name }}
          asset_name: cli-linux.zip
          overwrite: true

      - name: Rename Windows binary
        if: runner.os == 'Windows'
        run: mv apps/cli/dist/cli.exe apps/cli/dist/cli-windows.exe

      - name: Upload Windows Binary
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: cli-windows
          path: apps/cli/dist/cli-windows.exe

      - name: Zip Windows binary
        if: runner.os == 'Windows'
        uses: vimtor/action-zip@v1
        with:
          files: apps/cli/dist/cli-windows.exe
          dest: cli.zip

      - name: Release Windows binary Zip
        if: runner.os == 'Windows'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: BigDog1400/code0
          repo_token: ${{ secrets.TOKEN }}
          file: cli.zip
          tag: ${{ github.event.release.tag_name }}
          asset_name: cli-windows.zip
          overwrite: true

  release:
    name: Release to npm registry
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Download binaries
        uses: actions/download-artifact@v3

      - name: List directory
        working-directory: ./apps/cli
        run: ls -R

      - name: Publish to npm
        working-directory: ./apps/cli
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
